[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-core = { default-features = false,  path = "../../../primitives/core" }
sp-runtime = { default-features = false,  path = "../../../primitives/runtime" }

[dev-dependencies]
sp-serializer = { path = "../../../primitives/serializer" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]
