[package]
name = "pallet-elections-phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-phragmen = { default-features = false,  path = "../../primitives/phragmen" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
sp-std = { default-features = false,  path = "../../primitives/std" }

[dev-dependencies]
sp-io = { path = "../../primitives/io" }
hex-literal = "0.2.1"
pallet-balances = { path = "../balances" }
sp-core = { path = "../../primitives/core" }
substrate-test-utils = { path = "../../test-utils" }
serde = { version = "1.0.101" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-phragmen/std",
	"frame-system/std",
	"sp-std/std",
]
