[package]
name = "sp-authority-discovery"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Authority discovery primitives"
edition = "2018"

[dependencies]
sp-application-crypto = { default-features = false,  path = "../application-crypto" }
codec = { package = "parity-scale-codec", default-features = false, version = "1.0.3" }
sp-std = { default-features = false,  path = "../std" }
sp-api = { default-features = false,  path = "../api" }
sp-runtime = { default-features = false,  path = "../runtime" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std"
]
