[package]
name = "substrate-test-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
sp-application-crypto = { default-features = false,  path = "../../primitives/application-crypto" }
sp-consensus-aura = { default-features = false,  path = "../../primitives/consensus/aura" }
sp-consensus-babe = { default-features = false,  path = "../../primitives/consensus/babe" }
sp-block-builder = { default-features = false,  path = "../../primitives/block-builder" }
cfg-if = "0.1.10"
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
frame-executive = { default-features = false,  path = "../../frame/executive" }
sp-inherents = { default-features = false,  path = "../../primitives/inherents" }
sp-keyring = { optional = true,  path = "../../primitives/keyring" }
log = { version = "0.4.8", optional = true }
memory-db = { version = "0.15.2", default-features = false }
sp-offchain = { path = "../../primitives/offchain", default-features = false}
sp-core = { default-features = false,  path = "../../primitives/core" }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-runtime-interface = { path = "../../primitives/runtime-interface", default-features = false}
sp-io = { default-features = false,  path = "../../primitives/io" }
frame-support = { default-features = false,  path = "../../frame/support" }
sp-version = { default-features = false,  path = "../../primitives/version" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-session = { default-features = false,  path = "../../primitives/session" }
sp-api = { default-features = false,  path = "../../primitives/api" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
pallet-babe = { default-features = false,  path = "../../frame/babe" }
frame-system = { default-features = false,  path = "../../frame/system" }
frame-system-rpc-runtime-api = { default-features = false,  path = "../../frame/system/rpc/runtime-api" }
pallet-timestamp = { default-features = false,  path = "../../frame/timestamp" }
sc-client = { optional = true,  path = "../../client" }
sp-trie = { default-features = false,  path = "../../primitives/trie" }
sp-transaction-pool = { default-features = false,  path = "../../primitives/transaction-pool" }
trie-db = { version = "0.16.0", default-features = false }

[dev-dependencies]
sc-executor = { path = "../../client/executor" }
substrate-test-runtime-client = { path = "./client" }
sp-state-machine = { path = "../../primitives/state-machine" }

[build-dependencies]
wasm-builder-runner = { version = "1.0.4",  package = "substrate-wasm-builder-runner", path = "../../utils/wasm-builder-runner" }

[features]
default = [
	"std",
]
std = [
	"sp-application-crypto/std",
	"sp-consensus-aura/std",
	"sp-consensus-babe/std",
	"sp-block-builder/std",
	"codec/std",
	"frame-executive/std",
	"sp-inherents/std",
	"sp-keyring",
	"log",
	"memory-db/std",
	"sp-offchain/std",
	"sp-core/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime-interface/std",
	"sp-io/std",
	"frame-support/std",
	"sp-version/std",
	"serde",
	"sp-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"pallet-babe/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sc-client",
	"sp-trie/std",
	"sp-transaction-pool/std",
	"trie-db/std",
]
