[package]
name = "sp-runtime-interface-test-wasm"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
sp-runtime-interface = { default-features = false,  path = "../" }
sp-std = { default-features = false,  path = "../../std" }
sp-io = { default-features = false,  path = "../../io" }
sp-core = { default-features = false,  path = "../../core" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3", path = "../../../utils/wasm-builder-runner" }

[features]
default = [ "std" ]
std = [ "sp-runtime-interface/std", "sp-std/std", "sp-core/std", "sp-io/std" ]
