[package]
name = "paint-contracts-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "sc-client", path = "../../../client/" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
primitives = { package = "sp-core",  path = "../../../primitives/core" }
rpc-primitives = { package = "sp-rpc", path = "../../../primitives/rpc" }
serde = { version = "1.0.101", features = ["derive"] }
sp-runtime = { path = "../../../primitives/sr-primitives" }
sp-api = { path = "../../../primitives/sr-api" }
paint-contracts-rpc-runtime-api = { path = "./runtime-api" }
