[package]
name = "pallet-finality-tracker"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-inherents = { default-features = false,  path = "../../primitives/inherents" }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-finality-tracker = { default-features = false,  path = "../../primitives/finality-tracker" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
impl-trait-for-tuples = "0.1.3"

[dev-dependencies]
sp-core = { default-features = false,  path = "../../primitives/core" }
sp-io = { default-features = false,  path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"sp-std/std",
	"frame-support/std",
	"sp-runtime/std",
	"frame-system/std",
	"sp-finality-tracker/std",
	"sp-inherents/std",
]
