[package]
name = "substrate-transaction-pool-runtime-api"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sr-primitives = { path = "../../../primitives/sr-primitives", default-features = false }
primitives = { package = "substrate-primitives",  path = "../../primitives/core", default-features = false }
sr-api = { path = "../../../primitives/sr-api", default-features = false }

[features]
default = [ "std" ]
std = [ "sr-primitives/std", "primitives/std", "sr-api/std" ]
