[package]
name = "sp-transaction-pool"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-runtime = { path = "../../../primitives/sr-primitives", default-features = false }
primitives = { package = "sp-core",  path = "../../primitives/core", default-features = false }
sp-api = { path = "../../../primitives/sr-api", default-features = false }

[features]
default = [ "std" ]
std = [ "sp-runtime/std", "primitives/std", "sp-api/std" ]
