[package]
name = "pallet-authority-discovery"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-authority-discovery = { default-features = false,  path = "../../primitives/authority-discovery" }
sp-application-crypto = { default-features = false,  path = "../../primitives/application-crypto" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-core = { default-features = false,  path = "../../primitives/core" }
sp-std = { default-features = false,  path = "../../primitives/std" }
serde = { version = "1.0.101", optional = true }
sp-io = { default-features = false,  path = "../../primitives/io" }
pallet-session = { features = ["historical" ],  path = "../session", default-features = false }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }

[dev-dependencies]
sp-staking = { default-features = false,  path = "../../primitives/staking" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"sp-authority-discovery/std",
	"codec/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"serde",
	"pallet-session/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
