[package]
name = "sp-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-api = { default-features = false,  path = "../api" }
sp-std = { default-features = false,  path = "../std" }
sp-runtime = { optional = true,  path = "../runtime" }

[features]
default = [ "std" ]
std = [ "sp-api/std", "sp-std/std", "sp-runtime" ]
