[package]
name = "sp-authorship"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Authorship primitives"
edition = "2018"

[dependencies]
sp-inherents = { default-features = false,  path = "../inherents" }
sp-runtime = { default-features = false,  path = "../runtime" }
sp-std = { default-features = false,  path = "../std" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-std/std",
	"sp-inherents/std",
	"sp-runtime/std",
]
