[package]
name = "pallet-randomness-collective-flip"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
safe-mix = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
sp-std = { default-features = false,  path = "../../primitives/std" }

[dev-dependencies]
sp-core = { path = "../../primitives/core" }
sp-io = { path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"safe-mix/std",
	"frame-system/std",
	"codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
]
