[package]
name = "node-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }

# primitives
sp-authority-discovery = { default-features = false,  path = "../../../primitives/authority-discovery" }
sp-consensus-babe = { default-features = false,  path = "../../../primitives/consensus/babe" }
sp-block-builder = { path = "../../../primitives/block-builder", default-features = false}
sp-inherents = { default-features = false,  path = "../../../primitives/inherents" }
node-primitives = { default-features = false,  path = "../primitives" }
sp-offchain = { default-features = false,  path = "../../../primitives/offchain" }
sp-core = { default-features = false,  path = "../../../primitives/core" }
sp-std = { default-features = false,  path = "../../../primitives/std" }
sp-api = { default-features = false,  path = "../../../primitives/api" }
sp-runtime = { default-features = false,  path = "../../../primitives/runtime" }
sp-staking = { default-features = false,  path = "../../../primitives/staking" }
sp-keyring = { optional = true,  path = "../../../primitives/keyring" }
sp-session = { default-features = false,  path = "../../../primitives/session" }
sp-transaction-pool = { default-features = false,  path = "../../../primitives/transaction-pool" }
sp-version = { default-features = false,  path = "../../../primitives/version" }

# frame dependencies
pallet-authority-discovery = { default-features = false,  path = "../../../frame/authority-discovery" }
pallet-authorship = { default-features = false,  path = "../../../frame/authorship" }
pallet-babe = { default-features = false,  path = "../../../frame/babe" }
pallet-balances = { default-features = false,  path = "../../../frame/balances" }
pallet-collective = { default-features = false,  path = "../../../frame/collective" }
pallet-contracts = { default-features = false,  path = "../../../frame/contracts" }
pallet-contracts-rpc-runtime-api = { default-features = false,  path = "../../../frame/contracts/rpc/runtime-api/" }
pallet-democracy = { default-features = false,  path = "../../../frame/democracy" }
pallet-elections-phragmen = { default-features = false,  path = "../../../frame/elections-phragmen" }
frame-executive = { default-features = false,  path = "../../../frame/executive" }
pallet-finality-tracker = { default-features = false,  path = "../../../frame/finality-tracker" }
pallet-grandpa = { default-features = false,  path = "../../../frame/grandpa" }
pallet-im-online = { default-features = false,  path = "../../../frame/im-online" }
pallet-indices = { default-features = false,  path = "../../../frame/indices" }
pallet-membership = { default-features = false,  path = "../../../frame/membership" }
pallet-nicks = { default-features = false,  path = "../../../frame/nicks" }
pallet-offences = { default-features = false,  path = "../../../frame/offences" }
pallet-randomness-collective-flip = { default-features = false,  path = "../../../frame/randomness-collective-flip" }
pallet-session = { features = ["historical"],  path = "../../../frame/session", default-features = false }
pallet-staking = { features = ["migrate"],  path = "../../../frame/staking", default-features = false }
pallet-staking-reward-curve = { path = "../../../frame/staking/reward-curve"}
pallet-sudo = { default-features = false,  path = "../../../frame/sudo" }
frame-support = { default-features = false,  path = "../../../frame/support" }
frame-system = { default-features = false,  path = "../../../frame/system" }
frame-system-rpc-runtime-api = { default-features = false,  path = "../../../frame/system/rpc/runtime-api/" }
pallet-timestamp = { default-features = false,  path = "../../../frame/timestamp" }
pallet-treasury = { default-features = false,  path = "../../../frame/treasury" }
frame-utility = { default-features = false,  path = "../../../frame/utility" }
pallet-transaction-payment = { default-features = false,  path = "../../../frame/transaction-payment" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false,  path = "../../../frame/transaction-payment/rpc/runtime-api/" }

[build-dependencies]
wasm-builder-runner = { version = "1.0.4",  package = "substrate-wasm-builder-runner", path = "../../../utils/wasm-builder-runner" }

[dev-dependencies]
sp-io = { path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-contracts/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-membership/std",
	"pallet-nicks/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"frame-utility/std",
	"sp-version/std",
]
