[package]
name = "sp-consensus-aura"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
sp-application-crypto = { default-features = false,  path = "../../application-crypto" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-std = { default-features = false,  path = "../../std" }
sp-api = { default-features = false,  path = "../../api" }
sp-runtime = { default-features = false,  path = "../../runtime" }
sp-inherents = { default-features = false,  path = "../../inherents" }
sp-timestamp = { default-features = false,   path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-inherents/std",
	"sp-timestamp/std",
]
