[package]
name = "pallet-evm"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
pallet-timestamp = { default-features = false,  path = "../timestamp" }
pallet-balances = { default-features = false,  path = "../balances" }
sp-core = { default-features = false,  path = "../../primitives/core" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-io = { default-features = false,  path = "../../primitives/io" }
primitive-types = { version = "0.6", default-features = false, features = ["rlp"] }
rlp = { version = "0.4", default-features = false }
evm = { version = "0.14", default-features = false }
sha3 = { version = "0.8", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-io/std",
	"sp-std/std",
	"sha3/std",
	"rlp/std",
	"primitive-types/std",
	"evm/std",
	"pallet-timestamp/std",
]
