[package]
name = "pallet-im-online"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-application-crypto = { default-features = false,  path = "../../primitives/application-crypto" }
pallet-authorship = { default-features = false,  path = "../authorship" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-core = { default-features = false,  path = "../../primitives/core" }
sp-std = { default-features = false,  path = "../../primitives/std" }
serde = { version = "1.0.101", optional = true }
pallet-session = { default-features = false,  path = "../session" }
sp-io = { default-features = false,  path = "../../primitives/io" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-staking = { default-features = false,  path = "../../primitives/staking" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }

[features]
default = ["std", "pallet-session/historical"]
std = [
	"sp-application-crypto/std",
	"pallet-authorship/std",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"serde",
	"pallet-session/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-support/std",
	"frame-system/std",
]
