[package]
name = "pallet-authorship"
version = "0.1.0"
description = "Block and Uncle Author tracking for the SRML"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-core = { default-features = false,  path = "../../primitives/core" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-inherents = { default-features = false,  path = "../../primitives/inherents" }
sp-authorship = { default-features = false,  path = "../../primitives/authorship" }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
sp-io ={ path = "../../primitives/io", default-features = false }
impl-trait-for-tuples = "0.1.3"

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-authorship/std",
]
