[package]
name = "sp-api"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-api-proc-macro = { path = "proc-macro" }
sp-core = { default-features = false,  path = "../core" }
sp-std = { default-features = false,  path = "../std" }
sp-runtime = { default-features = false,  path = "../runtime" }
sp-version = { default-features = false,  path = "../version" }
sp-state-machine = { optional = true,  path = "../../primitives/state-machine" }

[dev-dependencies]
sp-test-primitives = { path = "../test-primitives" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-state-machine",
	"sp-version/std",
]
