[package]
name = "pallet-babe"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-inherents = { default-features = false,  path = "../../primitives/inherents" }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-staking = { default-features = false,  path = "../../primitives/staking" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
pallet-timestamp = { default-features = false,  path = "../timestamp" }
sp-timestamp = { default-features = false,  path = "../../primitives/timestamp" }
pallet-session = { default-features = false,  path = "../session" }
sp-consensus-babe = { default-features = false,  path = "../../primitives/consensus/babe" }
sp-io ={ path = "../../primitives/io", default-features = false }

[dev-dependencies]
lazy_static = "1.4.0"
parking_lot = "0.9.0"
sp-version = { default-features = false,  path = "../../primitives/version" }
sp-core = { path = "../../primitives/core" }
substrate-test-runtime = { path = "../../test-utils/runtime" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sp-timestamp/std",
	"sp-inherents/std",
	"sp-consensus-babe/std",
	"pallet-session/std",
	"sp-io/std",
]
