[package]
name = "pallet-offences"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pallet-balances = { default-features = false,  path = "../balances" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { default-features = false,  path = "../../primitives/std" }
serde = { version = "1.0.101", optional = true }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
sp-staking = { default-features = false,  path = "../../primitives/staking" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }

[dev-dependencies]
sp-io = { path = "../../primitives/io" }
sp-core = { path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"pallet-balances/std",
	"codec/std",
	"sp-std/std",
	"serde",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-support/std",
	"frame-system/std",
]
