[package]
name = "sp-consensus-babe"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"

[dependencies]
sp-application-crypto = { default-features = false,  path = "../../application-crypto" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-std = { default-features = false,  path = "../../std" }
schnorrkel = { version = "0.8.5", features = ["preaudit_deprecated"], optional = true }
sp-api = { default-features = false,  path = "../../api" }
sp-consensus = { optional = true,  path = "../common" }
sp-inherents = { default-features = false,  path = "../../inherents" }
sp-runtime = { default-features = false,   path = "../../runtime" }
sp-timestamp = { default-features = false,  path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"schnorrkel",
	"sp-api/std",
	"sp-consensus",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-timestamp/std",
]
