[package]
name = "pallet-assets"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
# Needed for various traits. In our case, `OnFinalize`.
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
# Needed for type-safe access to storage DB.
frame-support = { default-features = false,  path = "../support" }
# `system` module provides us with all sorts of useful stuff and macros depend on it being around.
frame-system = { default-features = false,  path = "../system" }

[dev-dependencies]
sp-core = { path = "../../primitives/core" }
sp-std = { path = "../../primitives/std" }
sp-io = { path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
