[package]
name = "pallet-treasury"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { default-features = false,  path = "../../primitives/std" }
sp-runtime = { default-features = false,  path = "../../primitives/runtime" }
frame-support = { default-features = false,  path = "../support" }
frame-system = { default-features = false,  path = "../system" }
pallet-balances = { default-features = false,  path = "../balances" }

[dev-dependencies]
sp-io ={ path = "../../primitives/io" }
sp-core = { path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
]
